// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4bxfaRDFmdmJfq14jxkWa-RWOCc16KIA',
    appId: '1:898417842708:web:09aa5634f753b6c5bfe501',
    messagingSenderId: '898417842708',
    projectId: 'instagram-clone-70063',
    authDomain: 'instagram-clone-70063.firebaseapp.com',
    storageBucket: 'instagram-clone-70063.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRkqqyopUvmAA8icjHYh0154X5fb4kHik',
    appId: '1:898417842708:android:154634ef69b94704bfe501',
    messagingSenderId: '898417842708',
    projectId: 'instagram-clone-70063',
    storageBucket: 'instagram-clone-70063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcSbpYtciqtbLei7_GJ4JZ1vwhT9c3z8Y',
    appId: '1:898417842708:ios:d9ec385578224645bfe501',
    messagingSenderId: '898417842708',
    projectId: 'instagram-clone-70063',
    storageBucket: 'instagram-clone-70063.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcSbpYtciqtbLei7_GJ4JZ1vwhT9c3z8Y',
    appId: '1:898417842708:ios:bcaa750df2221fd7bfe501',
    messagingSenderId: '898417842708',
    projectId: 'instagram-clone-70063',
    storageBucket: 'instagram-clone-70063.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
